name: weather_preview_app
description: "Simple app example. Bloc, dio, goRouter, etc."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  get_it: ^7.6.7
  go_router: ^13.0.1
  json_annotation: ^4.8.1
  permission_handler: ^11.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  yandex_mapkit: ^4.0.2

dev_dependencies:
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.1.5
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf
        - asset: assets/fonts/montserrat_light.ttf
        - asset: assets/fonts/montserrat_medium.ttf
        - asset: assets/fonts/montserrat_regular.ttf
        - asset: assets/fonts/montserrat_thin.ttf
